name: test-workflow
run-name: "Run name"
on:
  # schedule:
  #   - cron: 0 0 * * *
  # workflow_dispatch: 
  push:
    branches: 
      - feature/*
    branches-ignore: 
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test Script
        run: ls
        shell: bash