# name: test-workflow
# run-name: "Run name"
# on:
#   schedule:
#     - cron: 0 0 * * *
#   workflow_dispatch: 
#   push:
#     branches-ignore: 
#       - "**"
#     branches: 
#       - main
#       - 'feature/*'
#     paths: 
#       - '.github/**'

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4